teller_account_homepage:
    path:     /dashboard
    defaults: { _controller: TellerAccountBundle:Default:index }
teller_account_add:
    path: /dashboard/add
    defaults: { _controller: TellerAccountBundle:Default:add }
report:
    path: /dashboard/report
    defaults: { _controller: TellerAccountBundle:Default:report }
currency:
    path: /dashboard/currency
    defaults: { _controller: TellerAccountBundle:Default:currency }
